### ISSUE TITLE
JUnit 5 dependency not usually present in main sourceSet

### ISSUE THREAD

**Issue by nicksouthwell** [Softeq/itest-gradle-plugin#11]
Code would not compile and run due to missing JUnit 5 dependency (not included in main sourceSet)
Fixed by using test sourceSet in my project's build.gradle
itestSourceSet {
    compileClasspath = sourceSets.test.compileClasspath
    runtimeClasspath = sourceSets.test.runtimeClasspath
}

**Comment by idrabenia** [comment]
Hi @nicksouthwell ,

Thank you for the feedback!

Usually it is expected that JUnit 5 dependencies will be present in **itest-*** dependencies. There are just the same approach like provided by usual Gradle **test plugin**.

```groovy
dependencies {
    itestImplementation "org.junit.jupiter:junit-jupiter-api:$junitVersion"
    itestRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:$junitVersion"
}
```

But you approach is also make sense!

Best Regards,
Ilya
